[package]
name = "rust_shell"
version = "0.1.0"
authors = ["Niranjana <niranjana687>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shells = "0.2.0"